<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/circuito" elementFormDefault="qualified" targetNamespace="http://tempuri.org/circuito" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="circuito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datos" />
        <xs:element ref="tramos" />
        <xs:element ref="resultados" />
      </xs:sequence>
      <xs:attribute name="nombreCircuito" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="datos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitudCircuito" />
        <xs:element ref="anchura" />
        <xs:element ref="fechaCarrera" />
        <xs:element ref="horaCarreraEsp" />
        <xs:element ref="vueltas" />
        <xs:element ref="localidad" />
        <xs:element ref="pais" />
        <xs:element ref="patrocinador" />
        <xs:element ref="referencias" />
        <xs:element ref="multimedia" />
        <xs:element ref="coordenadasCircuito" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitudCircuito">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="anchura">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="unidad" type="xs:ID" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="fechaCarrera" type="xs:string" />
  <xs:element name="horaCarreraEsp" type="xs:string" />
  <xs:element name="vueltas" type="xs:string" />
  <xs:element name="localidad" type="xs:string" />
  <xs:element name="pais" type="xs:string" />
  <xs:element name="patrocinador" type="xs:string" />
  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencia" type="xs:string" />
  <xs:element name="multimedia">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="foto" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="video" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="foto" type="xs:string" />
  <xs:element name="video" type="xs:string" />
  <xs:element name="coordenadasCircuito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitud" />
        <xs:element ref="latitud" />
        <xs:element ref="altitud" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tramos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="tramo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tramo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="distancia" />
        <xs:element ref="coordenadasTramoFin" />
        <xs:element ref="sector" />
      </xs:sequence>
      <xs:attribute name="numeroTramo" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="distancia">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="coordenadasTramoFin">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitud" />
        <xs:element ref="latitud" />
        <xs:element ref="altitud" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sector" type="xs:string" />
  <xs:element name="longitud">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="latitud">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="altitud">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="resultados">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ganador" />
        <xs:element ref="tiempoGP" />
        <xs:element ref="clasificacion" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ganador" type="xs:string" />
  <xs:element name="tiempoGP">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="clasificacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="piloto" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="piloto">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="posicion" type="xs:string" use="required" />
          <xs:attribute name="puntos" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>