<!ELEMENT circuito  (datos, tramos, resultados)>
        <!ELEMENT datos (longitudCircuito, anchura,
                fechaCarrera, horaCarreraEsp, vueltas, 
                localidad, pais, patrocinador, 
                referencia+, foto+, video*, 
                coordenadasCircuito)>

        <!ELEMENT longitudCircuito (#PCDATA)>
        <!ELEMENT anchura (#PCDATA)>
        <!ELEMENT fechaCarrera (#PCDATA)>
        <!ELEMENT horaCarreraEsp (#PCDATA)>
        <!ELEMENT vueltas (#PCDATA)>
        <!ELEMENT localidad (#PCDATA)>
        <!ELEMENT pais (#PCDATA)>
        <!ELEMENT patrocinador (#PCDATA)>
        <!ELEMENT referencia (#PCDATA)>
        <!ELEMENT foto (#PCDATA)>
        <!ELEMENT video (#PCDATA)>
        <!ELEMENT coordenadasCircuito (longitud, latitud, altitud)>

        <!ELEMENT tramos (tramo*)>
        <!ELEMENT tramo (distancia, coordenadasTramoFin, sector)>
        <!ELEMENT distancia (#PCDATA)>
        <!ELEMENT coordenadasTramoFin (longitud, latitud, altitud)>
        <!ELEMENT sector (#PCDATA)>


        <!ELEMENT longitud (#PCDATA)>
        <!ELEMENT latitud (#PCDATA)>
        <!ELEMENT altitud (#PCDATA)>

        <!ELEMENT resultados (ganador, tiempoGP, clasificacion)>
        <!ELEMENT ganador (#PCDATA)>
        <!ELEMENT tiempoGP (#PCDATA)>
        <!ELEMENT clasificacion (piloto*)>
        <!ELEMENT piloto (#PCDATA)>

        <!ATTLIST circuito
                nombreCircuito CDATA #REQUIRED>
        <!ATTLIST tramo
                numeroTramo CDATA #REQUIRED>
        <!ATTLIST piloto
                posicion CDATA #REQUIRED
                puntos CDATA #REQUIRED>
        <!ATTLIST tiempoGP
                unidad CDATA #REQUIRED>
        <!ATTLIST longitudCircuito
                unidad  CDATA #REQUIRED>
        <!ATTLIST anchura 
                unidad ID #REQUIRED>
        <!ATTLIST distancia
                unidad  CDATA #REQUIRED>
        <!ATTLIST longitud
                unidad  CDATA #REQUIRED>
        <!ATTLIST latitud
                unidad  CDATA #REQUIRED>
        <!ATTLIST altitud
                unidad  CDATA #REQUIRED>
                